name: Update systeminformer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 5'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Bump the systeminformer version
      run: ./update.sh
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
